language: java
mvn test -B
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

sudo: false
install: true
addons:
  sonarcloud:
    organization: "luizhsaggin"
    
jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
